# Generated by Django 3.2.16 on 2023-07-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('taste', models.IntegerField(choices=[(1, '1 звездочек'), (2, '2 звездочек'), (3, '3 звездочек'), (4, '4 звездочек'), (5, '5 звездочек'), (6, '6 звездочек'), (7, '7 звездочек'), (8, '8 звездочек'), (9, '9 звездочек'), (10, '10 звездочек')], default=0, verbose_name='Вкус')),
                ('price', models.IntegerField(choices=[(1, '1 звездочек'), (2, '2 звездочек'), (3, '3 звездочек'), (4, '4 звездочек'), (5, '5 звездочек'), (6, '6 звездочек'), (7, '7 звездочек'), (8, '8 звездочек'), (9, '9 звездочек'), (10, '10 звездочек')], default=0, verbose_name='Вкус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Накиньте пару слов об этом пивке')),
                ('total_rate', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='beer_images', verbose_name='Фото')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
